### ISSUE TITLE
hi, need help

### ISSUE THREAD

**Issue by karthiceaswar** [nishanthshastry/Interactive-Student-Faculty-Networking-Platform-DBMS#1]
hi , i am doing BE CSE 2 nd year and interested in your project
if you can provide me with the source and the word document of the pdf and the ER diagram it would be helpful. Thankyou

**Comment by nishanthshastry** [comment]
hi, the source codes and the document pdf are already present in the repository....
thank you for your interest in the project....

**Comment by karthiceaswar** [comment]
can i have the word document of the pdf and the raw ER diagram?
